[package]
name = "day22"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.12.2"
rayon = "1.10.0"
indicatif = { version = "0.18.2", features = ["rayon"] }